# Documentation - https://github.com/actions/labeler

# General Labels
.github:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
build:
- all: # all are AND-ed together
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '*.sln'
      - '**/*.sln'
      - '*.vcxproj*'
      - '**/*.vcxproj*'
      - 'building/*'
      - 'cmake/*'
      - 'CMakeLists.txt'
      - 'data/*'
      - 'docs/*'
      - '**/CMakeLists.txt'
      - '*.sh'
    - all-globs-to-all-files:
      - '!external/**'
document:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - '**/*.md'
      - '*.pdf'
      - '**/*.pdf'
    - all-globs-to-all-files:
      - '!external/**'
external:
  - changed-files:
    - any-glob-to-any-file:
      - 'external/**'
tools:
  - changed-files:
    - any-glob-to-any-file:
      - 'tools/**'

# RPCSV Labels
app:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/app/**'
audio:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/audio/**'
codec:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/codec/**'
compat:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/compat/**'
config:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/config/**'
cpu:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/cpu/**'
ctrl:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/ctrl/**'
debug:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/gdbstub/**'
      - 'RPCSV/**/tracy.cpp'
dialog:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/dialog/**'
display:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/display/**'
emuenv:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/emuenv/**'
features:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/features/**'
gdbstub:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/gdbstub/**'
gxm:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/gxm/**'
hle:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/module/**'
      - 'RPCSV/modules/**'
host:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/host/**'
http:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/http/**'
ime:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/ime/**'
io:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/io/**'
kernel:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/kernel/**'
memory:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/mem/**'
module:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/module/**'
modules:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/modules/**'
motion:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/motion/**'
net:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/net/**'
ngs:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/ngs/**'
nids:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/nids/**'
np:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/np/**'
opengl:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/renderer/**/gl/**'
      - 'RPCSV/glutil/**'
packages:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/packages/**'
patch:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/patch/**'
regmgr:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/regmgr/**'
renderer:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/renderer/**'
rtc:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/rtc/**'
script:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/script/**'
shader:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/shader/**'
      - 'RPCSV/shaders-builtin/**'
texture:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/renderer/src/texture/**'
threads:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/threads/**'
touch:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/touch/**'
util:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/util/**'
vulkan:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/renderer/**/vulkan/**'
      - 'RPCSV/vkutil/**'

# OS Labels
windows:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*windows*'
mac:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*macos*'
linux:
  - changed-files:
    - any-glob-to-any-file:
      - 'appimage/*'
      - '**/*linux*'

# GUI Labels
gui:
  - changed-files:
    - any-glob-to-any-file:
      - 'RPCSV/gui/**'
gui/lang:
  - changed-files:
    - any-glob-to-any-file:
      - 'lang/**'
      - 'RPCSV/lang/**'
