// Vita3K emulator project
// Copyright (C) 2021 Vita3K team
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#pragma once

#include <module/module.h>

BRIDGE_DECL(FT_Activate_Size)
BRIDGE_DECL(FT_Add_Default_Modules)
BRIDGE_DECL(FT_Add_Module)
BRIDGE_DECL(FT_Alloc)
BRIDGE_DECL(FT_Angle_Diff)
BRIDGE_DECL(FT_Atan2)
BRIDGE_DECL(FT_Attach_File)
BRIDGE_DECL(FT_Attach_Stream)
BRIDGE_DECL(FT_Bitmap_Convert)
BRIDGE_DECL(FT_Bitmap_Copy)
BRIDGE_DECL(FT_Bitmap_Done)
BRIDGE_DECL(FT_Bitmap_Embolden)
BRIDGE_DECL(FT_Bitmap_New)
BRIDGE_DECL(FT_CMap_Done)
BRIDGE_DECL(FT_CMap_New)
BRIDGE_DECL(FT_CeilFix)
BRIDGE_DECL(FT_Cos)
BRIDGE_DECL(FT_DivFix)
BRIDGE_DECL(FT_Done_Face)
BRIDGE_DECL(FT_Done_FreeType)
BRIDGE_DECL(FT_Done_Glyph)
BRIDGE_DECL(FT_Done_GlyphSlot)
BRIDGE_DECL(FT_Done_Library)
BRIDGE_DECL(FT_Done_Memory)
BRIDGE_DECL(FT_Done_Size)
BRIDGE_DECL(FT_Face_GetCharVariantIndex)
BRIDGE_DECL(FT_Face_GetCharVariantIsDefault)
BRIDGE_DECL(FT_Face_GetCharsOfVariant)
BRIDGE_DECL(FT_Face_GetVariantSelectors)
BRIDGE_DECL(FT_Face_GetVariantsOfChar)
BRIDGE_DECL(FT_FloorFix)
BRIDGE_DECL(FT_Free)
BRIDGE_DECL(FT_Get_Advance)
BRIDGE_DECL(FT_Get_Advances)
BRIDGE_DECL(FT_Get_CMap_Format)
BRIDGE_DECL(FT_Get_CMap_Language_ID)
BRIDGE_DECL(FT_Get_Char_Index)
BRIDGE_DECL(FT_Get_Charmap_Index)
BRIDGE_DECL(FT_Get_First_Char)
BRIDGE_DECL(FT_Get_Glyph)
BRIDGE_DECL(FT_Get_Glyph_Name)
BRIDGE_DECL(FT_Get_Kerning)
BRIDGE_DECL(FT_Get_Module)
BRIDGE_DECL(FT_Get_Module_Interface)
BRIDGE_DECL(FT_Get_Name_Index)
BRIDGE_DECL(FT_Get_Next_Char)
BRIDGE_DECL(FT_Get_Postscript_Name)
BRIDGE_DECL(FT_Get_Renderer)
BRIDGE_DECL(FT_Get_Sfnt_Name)
BRIDGE_DECL(FT_Get_Sfnt_Name_Count)
BRIDGE_DECL(FT_Get_Sfnt_Table)
BRIDGE_DECL(FT_Get_SubGlyph_Info)
BRIDGE_DECL(FT_Get_Track_Kerning)
BRIDGE_DECL(FT_Get_TrueType_Engine_Type)
BRIDGE_DECL(FT_GlyphLoader_Add)
BRIDGE_DECL(FT_GlyphLoader_CheckPoints)
BRIDGE_DECL(FT_GlyphLoader_CheckSubGlyphs)
BRIDGE_DECL(FT_GlyphLoader_CopyPoints)
BRIDGE_DECL(FT_GlyphLoader_CreateExtra)
BRIDGE_DECL(FT_GlyphLoader_Done)
BRIDGE_DECL(FT_GlyphLoader_New)
BRIDGE_DECL(FT_GlyphLoader_Prepare)
BRIDGE_DECL(FT_GlyphLoader_Reset)
BRIDGE_DECL(FT_GlyphLoader_Rewind)
BRIDGE_DECL(FT_GlyphSlot_Own_Bitmap)
BRIDGE_DECL(FT_Glyph_Copy)
BRIDGE_DECL(FT_Glyph_Get_CBox)
BRIDGE_DECL(FT_Glyph_To_Bitmap)
BRIDGE_DECL(FT_Glyph_Transform)
BRIDGE_DECL(FT_Library_Version)
BRIDGE_DECL(FT_List_Add)
BRIDGE_DECL(FT_List_Finalize)
BRIDGE_DECL(FT_List_Find)
BRIDGE_DECL(FT_List_Insert)
BRIDGE_DECL(FT_List_Iterate)
BRIDGE_DECL(FT_List_Remove)
BRIDGE_DECL(FT_List_Up)
BRIDGE_DECL(FT_Load_Char)
BRIDGE_DECL(FT_Load_Glyph)
BRIDGE_DECL(FT_Load_Sfnt_Table)
BRIDGE_DECL(FT_Lookup_Renderer)
BRIDGE_DECL(FT_Match_Size)
BRIDGE_DECL(FT_Matrix_Invert)
BRIDGE_DECL(FT_Matrix_Multiply)
BRIDGE_DECL(FT_Matrix_Multiply_Scaled)
BRIDGE_DECL(FT_MulDiv)
BRIDGE_DECL(FT_MulDiv_No_Round)
BRIDGE_DECL(FT_MulFix)
BRIDGE_DECL(FT_New_Face)
BRIDGE_DECL(FT_New_GlyphSlot)
BRIDGE_DECL(FT_New_Library)
BRIDGE_DECL(FT_New_Memory_Face)
BRIDGE_DECL(FT_New_Size)
BRIDGE_DECL(FT_OpenType_Validate)
BRIDGE_DECL(FT_Open_Face)
BRIDGE_DECL(FT_Outline_Check)
BRIDGE_DECL(FT_Outline_Copy)
BRIDGE_DECL(FT_Outline_Decompose)
BRIDGE_DECL(FT_Outline_Done)
BRIDGE_DECL(FT_Outline_Done_Internal)
BRIDGE_DECL(FT_Outline_Embolden)
BRIDGE_DECL(FT_Outline_Get_Bitmap)
BRIDGE_DECL(FT_Outline_Get_CBox)
BRIDGE_DECL(FT_Outline_Get_Orientation)
BRIDGE_DECL(FT_Outline_New)
BRIDGE_DECL(FT_Outline_New_Internal)
BRIDGE_DECL(FT_Outline_Render)
BRIDGE_DECL(FT_Outline_Reverse)
BRIDGE_DECL(FT_Outline_Transform)
BRIDGE_DECL(FT_Outline_Translate)
BRIDGE_DECL(FT_QAlloc)
BRIDGE_DECL(FT_QRealloc)
BRIDGE_DECL(FT_Raccess_Get_DataOffsets)
BRIDGE_DECL(FT_Raccess_Get_HeaderInfo)
BRIDGE_DECL(FT_Raccess_Guess)
BRIDGE_DECL(FT_Realloc)
BRIDGE_DECL(FT_Reference_Face)
BRIDGE_DECL(FT_Reference_Library)
BRIDGE_DECL(FT_Remove_Module)
BRIDGE_DECL(FT_Render_Glyph)
BRIDGE_DECL(FT_Render_Glyph_Internal)
BRIDGE_DECL(FT_Request_Metrics)
BRIDGE_DECL(FT_Request_Size)
BRIDGE_DECL(FT_RoundFix)
BRIDGE_DECL(FT_Select_Charmap)
BRIDGE_DECL(FT_Select_Metrics)
BRIDGE_DECL(FT_Select_Size)
BRIDGE_DECL(FT_Set_Char_Size)
BRIDGE_DECL(FT_Set_Charmap)
BRIDGE_DECL(FT_Set_Debug_Hook)
BRIDGE_DECL(FT_Set_Pixel_Sizes)
BRIDGE_DECL(FT_Set_Renderer)
BRIDGE_DECL(FT_Set_Transform)
BRIDGE_DECL(FT_Sfnt_Table_Info)
BRIDGE_DECL(FT_Sin)
BRIDGE_DECL(FT_Sqrt32)
BRIDGE_DECL(FT_SqrtFixed)
BRIDGE_DECL(FT_Stream_Close)
BRIDGE_DECL(FT_Stream_EnterFrame)
BRIDGE_DECL(FT_Stream_ExitFrame)
BRIDGE_DECL(FT_Stream_ExtractFrame)
BRIDGE_DECL(FT_Stream_Free)
BRIDGE_DECL(FT_Stream_GetChar)
BRIDGE_DECL(FT_Stream_New)
BRIDGE_DECL(FT_Stream_Open)
BRIDGE_DECL(FT_Stream_OpenMemory)
BRIDGE_DECL(FT_Stream_Pos)
BRIDGE_DECL(FT_Stream_Read)
BRIDGE_DECL(FT_Stream_ReadAt)
BRIDGE_DECL(FT_Stream_ReadChar)
BRIDGE_DECL(FT_Stream_ReadFields)
BRIDGE_DECL(FT_Stream_ReleaseFrame)
BRIDGE_DECL(FT_Stream_Seek)
BRIDGE_DECL(FT_Stream_Skip)
BRIDGE_DECL(FT_Stream_TryRead)
BRIDGE_DECL(FT_Tan)
BRIDGE_DECL(FT_Vector_From_Polar)
BRIDGE_DECL(FT_Vector_Length)
BRIDGE_DECL(FT_Vector_Polarize)
BRIDGE_DECL(FT_Vector_Rotate)
BRIDGE_DECL(FT_Vector_Transform)
BRIDGE_DECL(FT_Vector_Transform_Scaled)
BRIDGE_DECL(FT_Vector_Unit)
