// Vita3K emulator project
// Copyright (C) 2021 Vita3K team
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#pragma once

#include <module/module.h>

BRIDGE_DECL(ksceKernelCancelCallback)
BRIDGE_DECL(ksceKernelCancelMsgPipe)
BRIDGE_DECL(ksceKernelCancelMutex)
BRIDGE_DECL(ksceKernelChangeCurrentThreadAttr)
BRIDGE_DECL(ksceKernelChangeThreadCpuAffinityMask)
BRIDGE_DECL(ksceKernelChangeThreadPriority)
BRIDGE_DECL(ksceKernelChangeThreadSuspendStatus)
// BRIDGE_DECL(ksceKernelCheckCallback)
// BRIDGE_DECL(ksceKernelCheckWaitableStatus)
BRIDGE_DECL(ksceKernelClearEvent)
BRIDGE_DECL(ksceKernelClearEventFlag)
BRIDGE_DECL(ksceKernelCreateCallback)
BRIDGE_DECL(ksceKernelCreateCond)
BRIDGE_DECL(ksceKernelCreateEventFlag)
BRIDGE_DECL(ksceKernelCreateMsgPipe)
BRIDGE_DECL(ksceKernelCreateMutex)
BRIDGE_DECL(ksceKernelCreateSema)
BRIDGE_DECL(ksceKernelCreateSimpleEvent)
BRIDGE_DECL(ksceKernelCreateThread)
// BRIDGE_DECL(ksceKernelDelayThread)
// BRIDGE_DECL(ksceKernelDelayThreadCB)
BRIDGE_DECL(ksceKernelDeleteCallback)
BRIDGE_DECL(ksceKernelDeleteCond)
BRIDGE_DECL(ksceKernelDeleteEventFlag)
BRIDGE_DECL(ksceKernelDeleteFastMutex)
BRIDGE_DECL(ksceKernelDeleteMsgPipe)
BRIDGE_DECL(ksceKernelDeleteMutex)
BRIDGE_DECL(ksceKernelDeleteSema)
BRIDGE_DECL(ksceKernelDeleteThread)
BRIDGE_DECL(ksceKernelEnqueueWorkQueue)
// BRIDGE_DECL(ksceKernelExitDeleteThread)
// BRIDGE_DECL(ksceKernelExitThread)
BRIDGE_DECL(ksceKernelGetCallbackCount)
BRIDGE_DECL(ksceKernelGetMutexInfo)
// BRIDGE_DECL(ksceKernelGetProcessId)
BRIDGE_DECL(ksceKernelGetProcessIdFromTLS)
BRIDGE_DECL(ksceKernelGetSystemTimeLow)
// BRIDGE_DECL(ksceKernelGetSystemTimeWide)
BRIDGE_DECL(ksceKernelGetTLSAddr)
BRIDGE_DECL(ksceKernelGetThreadCpuAffinityMask)
BRIDGE_DECL(ksceKernelGetThreadCpuRegisters)
BRIDGE_DECL(ksceKernelGetThreadCurrentPriority)
BRIDGE_DECL(ksceKernelGetThreadId)
BRIDGE_DECL(ksceKernelGetThreadIdList)
BRIDGE_DECL(ksceKernelGetThreadInfo)
BRIDGE_DECL(ksceKernelGetThreadStackFreeSize)
BRIDGE_DECL(ksceKernelGetThreadTLSAddr)
BRIDGE_DECL(ksceKernelGetThreadmgrUIDClass)
BRIDGE_DECL(ksceKernelGetTimerBaseWide)
BRIDGE_DECL(ksceKernelGetTimerTimeWide)
BRIDGE_DECL(ksceKernelInitializeFastMutex)
BRIDGE_DECL(ksceKernelLockFastMutex)
BRIDGE_DECL(ksceKernelLockMutex)
BRIDGE_DECL(ksceKernelLockMutexCB_089)
BRIDGE_DECL(ksceKernelNotifyCallback)
BRIDGE_DECL(ksceKernelPollEventFlag)
BRIDGE_DECL(ksceKernelPollSema)
BRIDGE_DECL(ksceKernelPulseEvent)
BRIDGE_DECL(ksceKernelPulseEventWithNotifyCallback)
BRIDGE_DECL(ksceKernelReceiveMsgPipeVector)
BRIDGE_DECL(ksceKernelReceiveMsgPipeVectorCB)
BRIDGE_DECL(ksceKernelRegisterCallbackToEvent)
BRIDGE_DECL(ksceKernelRegisterTimer)
BRIDGE_DECL(ksceKernelRunWithStack)
BRIDGE_DECL(ksceKernelSendMsgPipeVector)
BRIDGE_DECL(ksceKernelSetEvent)
BRIDGE_DECL(ksceKernelSetEventFlag)
BRIDGE_DECL(ksceKernelSetPermission)
BRIDGE_DECL(ksceKernelSetProcessId)
BRIDGE_DECL(ksceKernelSetTimerTimeWide)
BRIDGE_DECL(ksceKernelSignalCond)
BRIDGE_DECL(ksceKernelSignalCondAll)
BRIDGE_DECL(ksceKernelSignalCondTo)
BRIDGE_DECL(ksceKernelSignalSema)
BRIDGE_DECL(ksceKernelStartThread)
BRIDGE_DECL(ksceKernelStartTimer)
BRIDGE_DECL(ksceKernelStopTimer)
BRIDGE_DECL(ksceKernelTryLockMutex)
BRIDGE_DECL(ksceKernelTryLockReadRWLock)
BRIDGE_DECL(ksceKernelTryLockWriteRWLock)
BRIDGE_DECL(ksceKernelTryReceiveMsgPipeVector)
BRIDGE_DECL(ksceKernelTrySendMsgPipeVector)
BRIDGE_DECL(ksceKernelUnlockFastMutex)
BRIDGE_DECL(ksceKernelUnlockMutex)
BRIDGE_DECL(ksceKernelUnlockReadRWLock)
BRIDGE_DECL(ksceKernelUnlockWriteRWLock)
BRIDGE_DECL(ksceKernelUnregisterCallbackFromEvent)
BRIDGE_DECL(ksceKernelUnregisterCallbackFromEventAll)
// BRIDGE_DECL(ksceKernelUnregisterThreadEventHandler)
BRIDGE_DECL(ksceKernelWaitCond)
BRIDGE_DECL(ksceKernelWaitEvent)
BRIDGE_DECL(ksceKernelWaitEventCB)
BRIDGE_DECL(ksceKernelWaitEventFlag)
BRIDGE_DECL(ksceKernelWaitEventFlagCB)
BRIDGE_DECL(ksceKernelWaitSema)
BRIDGE_DECL(ksceKernelWaitThreadEnd)
BRIDGE_DECL(ksceKernelWaitThreadEndCB)
